version: "3.8"

networks:
  &network wlsnet:
    driver: bridge

services:
  adminserver:
    container_name: adminserver
    hostname: adminserver
    image: 12214-weblogic-domain-generic
    restart: "no" 
    environment:
      JAVA_HOME: "/usr/java/latest"
      CUSTOM_PRODUCTION_MODE_ENABLED: "false"
      CUSTOM_DOMAIN_NAME: daveDomain
      CUSTOM_DOMAIN_ROOT: /app/domains
      CUSTOM_DOMAIN_HOME: /app/domains/daveDomain
      CUSTOM_WEBLOGIC_USERNAME: weblogic
      CUSTOM_WEBLOGIC_PASSWORD: weblogic123
    ports:
      - "7001:7001"
      - "9002:9002"
    networks:
      - *network
    volumes:
      - /app/domains:/app/domains:z


  managedserver:
    container_name: managedserver    
    image: 12214-weblogic-domain-generic
    command: /u01/oracle/container-scripts/startManagedServer.sh 
    restart: "no" 
    environment:
      JAVA_HOME: "/usr/java/latest"
      CUSTOM_PRODUCTION_MODE_ENABLED: "false"
      CUSTOM_DOMAIN_HOME: /app/domains
      CUSTOM_WEBLOGIC_USERNAME: weblogic
      CUSTOM_WEBLOGIC_PASSWORD: weblogic123
    ports:
      - "8001:8001"
    depends_on:
      - adminserver

    networks:
      - *network
    volumes:
      - /app/domains:/app/domains:z  

  
