node {

    withMaven(maven:'local',
              options: [
        artifactsPublisher(disabled: true), 
        findbugsPublisher(disabled: true), 
        openTasksPublisher(disabled: true),
              junitPublisher(disabled: true)
              ]
             ) {

        stage('Checkout') {
          git url: 'https://github.com/dveselka/weblogic/', credentialsId: 'dave-devops', branch: 'weblogic-14.1.1'
        }

        stage('Build') {
            sh 'cd dave-basic-webapp-ejb-project; mvn clean package'
            

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
   

    }

}
