version: "3.8"

networks:
  &network wlsnet:
    driver: bridge

services:
  adminserver:
    container_name: adminserver    
    image: oracle/weblogic:12.2.1.4-generic
    restart: "no" 
    environment:
      CUSTOM_DOMAIN_NAME: myDomain
      CUSTOM_ADMIN_NAME: myadmin
      CUSTOM_ADMIN_PORT: 7001
      CUSTOM_ADMIN_HOST: AdminContainer
      CUSTOM_ADMINISTRATION_PORT_ENABLED: "false"
      CUSTOM_ADMINISTRATION_PORT: 9002
      CUSTOM_MANAGED_SERVER_PORT: 8001
      CUSTOM_MANAGED_SERVER_NAME_BASE: MS
      CUSTOM_CONFIGURED_MANAGED_SERVER_COUNT: 2
      CUSTOM_CLUSTER_NAME: cluster1
      CUSTOM_CLUSTER_TYPE: DYNAMIC
      CUSTOM_PRODUCTION_MODE_ENABLED: "false"
      CUSTOM_DOMAIN_HOME: /app/domains
      CUSTOM_WEBLOGIC_USER: weblogic
      CUSTOM_WEBLOGIC_PASSWORD: weblogic123
    ports:
      - "7001:7001"
      - "9002:9002"
    networks:
      - *network
    volumes:
      - /app/domains/properties:/u01/oracle/properties:z
      - /app/domains:/u01/oracle/user_projects/domains:z

volumes:
  adminserver:

  
